const aiResponses = {
  "hej": "Hej på dig!",
  "tja": "Tja! Hur är läget?",
  "hur mår du": "Jag mår bra, tack! Och du?",
  "vad heter du": "Jag heter WindskoreAI?",
  "sluta": "Hejdå! Vi ses nästa gång.",
  "god morgon": "God morgon! Hoppas du sovit gott!",
  "god natt": "God natt! Sov så gott!",
  "vad gör du": "Jag pratar med dig just nu!",
  "spelar du spel": "Ja, jag gillar spel! Vilket är ditt favoritspel?",
  "favoritfärg": "Jag gillar blått, det är lugnande.",
  "vad är klockan": "Jag har ingen klocka, men jag kan alltid gissa! 😄",
  "väder": "Jag hoppas solen skiner där du är!",
  "regn": "Regn är mysigt ibland, eller hur?",
  "sol": "Sol är alltid härligt!",
  "snö": "Snö kan vara vackert men kallt.",
  "roligt": "Jag älskar roliga saker!",
  "tråkigt": "Tråkigt kan man göra om till något kul!",
  "musik": "Jag gillar musik, speciellt lugn bakgrundsmusik.",
  "film": "Vilken typ av filmer gillar du?",
  "serie": "Serier är perfekt för en mysig kväll.",
  "mat": "Mat är livet! Vad gillar du att äta?",
  "pizza": "Pizza är alltid ett bra val!",
  "glass": "Glass på sommaren är bäst!",
  "hund": "Hundar är så söta!",
  "katt": "Katter är mysiga och självständiga.",
  "spel": "Vilket spel spelar du just nu?",
  "minecraft": "Minecraft är superkul! Vad bygger du?",
  "roblox": "Roblox är kul! Har du något eget spel där?",
  "programmering": "Programmering är spännande! Vilket språk använder du?",
  "javascript": "JavaScript är väldigt användbart för webben!",
  "lua": "Lua är perfekt för spelmodding och Roblox.",
  "c++": "C++ är kraftfullt men lite mer avancerat.",
  "python": "Python är enkelt och roligt att använda!",
  "html": "HTML är grunden för alla webbsidor.",
  "css": "CSS gör webben snygg och stilren.",
  "hemligt": "Shhh... det är hemligt!",
  "skämt": "Varför kan inte ett spöke ljuga? För man ser rakt igenom det! 😄",
  "gåta": "Vad har tänder men kan inte äta? Ett sågblad!",
  "robot": "Jag är en AI-robot, men vänlig såklart!",
  "AI": "Jag är en AI och jag gillar att prata med dig!",
  "framtid": "Framtiden är spännande, full av möjligheter!",
  "teknik": "Teknik gör livet enklare på många sätt.",
  "dator": "Jag älskar datorer, de är som mina vänner!",
  "mobil": "Mobiltelefoner är praktiska, men glöm inte vila från dem!",
  "internet": "Internet är stort, men vi kan hitta allt där!",
  "wifi": "WiFi är som luft för en dator.",
  "skola": "Skola är viktigt, men glöm inte ha kul också!",
  "läxa": "Läxor kan vara tråkiga, men de hjälper dig växa.",
  "lärare": "Lärare är fantastiska och lär oss mycket.",
  "vän": "Vänner är guld värda!",
  "familj": "Familj är viktigt, ta hand om dem!",
  "semester": "Semester är perfekt för att vila och ha kul.",
  "resa": "Resor är roliga och lärorika.",
  "bil": "Bilar är snabba och coola!",
  "cykel": "Cykla är både kul och nyttigt!",
  "flygplan": "Flygplan är fantastiska, de tar oss över världen!",
  "båt": "Båtar är mysiga på vattnet.",
  "hav": "Havet är stort och vackert!",
  "sjö": "Sjön är perfekt för en picknick eller simtur.",
  "berg": "Berg är mäktiga och imponerande.",
  "skog": "Skogen är lugn och fridfull.",
  "djur": "Djur är underbara och roliga att observera.",
  "fågel": "Fåglar kan vara vackra och sjunga fint.",
  "fisk": "Fiskar är fascinerande att titta på.",
  "äpple": "Äpplen är goda och nyttiga!",
  "banan": "Bananer är enkla att äta och ger energi.",
  "choklad": "Choklad är alltid gott!",
  "godis": "Godis kan vara festligt ibland!",
  "sport": "Sport är roligt och bra för kroppen.",
  "fotboll": "Fotboll är världens mest populära sport!",
  "basket": "Basket är kul och actionfyllt!",
  "tennis": "Tennis är både teknik och kraft.",
  "konst": "Konst är ett sätt att uttrycka sig.",
  "måla": "Måla är avslappnande och kreativt.",
  "rita": "Att rita är alltid kul!",
  "musikstil": "Vilken musikstil gillar du mest?",
  "dans": "Dans är roligt och energigivande!",
  "sång": "Sång kan göra folk glada.",
  "bok": "Böcker är som portaler till andra världar.",
  "läsning": "Att läsa är både roligt och lärorikt.",
  "filmkväll": "Filmkvällar är mysiga!",
  "bio": "Att gå på bio är alltid en upplevelse.",
  "shopping": "Shopping kan vara kul men tröttsamt!",
  "present": "Presenter gör folk glada.",
  "födelsedag": "Födelsedagar är speciella dagar!",
  "jul": "Jul är mysigt med familj och ljus.",
  "påsk": "Påsk handlar om ägg och roliga traditioner.",
  "sommar": "Sommar är perfekt för semester och sol.",
  "vår": "Vår är vacker med alla blommor.",
  "höst": "Höstens färger är fantastiska.",
  "vinter": "Vinter är mysigt med snö och varm choklad.",
  "semesterplaner": "Har du några roliga semesterplaner?",
  "dröm": "Drömmar kan vara både roliga och konstiga!",
  "idé": "Bra idé! Berätta mer.",
  "problem": "Problem är till för att lösas!",
  "hjälp": "Självklart, jag hjälper dig gärna!",
  "fråga": "Ställ din fråga, jag lyssnar!",
  "nyfiken": "Nyfikenhet är nyckeln till lärande!",
  "roligt skämt": "Varför kunde inte cykeln stå upp? Den var två-hjulig! 😄",
  "spelidé": "Berätta om din spelidé, jag är nyfiken!",
  "hej igen": "Hej igen! Kul att se dig!",
  "tjena": "Tjena! Hur går det?",
  "hejsan": "Hejsan! Vad gör du idag?",
  "god eftermiddag": "God eftermiddag! Hoppas dagen varit bra.",
  "god kväll": "God kväll! Mysigt att prata med dig.",
  "hur går det": "Det går bra, tack! Själv då?",
  "kul": "Ja, det är alltid kul med roliga saker!",
  "trist": "Trist kan man göra om till något roligt!",
  "spelplan": "Spelplanen är redo, låt oss spela!",
  "äventyr": "Äventyr låter spännande! Vart ska vi?",
  "resa dröm": "Jag drömmer om att resa till Mars!",
  "framtidsplan": "Framtiden är full av möjligheter!",
  "idéer": "Jag älskar nya idéer, berätta!",
  "nytt spel": "Ett nytt spel låter kul, berätta mer!",
  "projekt": "Projekt är roliga när man ser resultatet!",
  "mål": "Mål är viktiga för att hålla fokus!",
  "tävling": "Tävlingar är roliga och spännande!",
  "pris": "Vem gillar inte priser?",
  "vänskap": "Vänskap är guld värd!",
  "relationer": "Relationer behöver omsorg och tid.",
  "känsla": "Känslor gör livet färgstarkt!",
  "glad": "Härligt att vara glad!",
  "ledsen": "Det är okej att känna sig ledsen ibland.",
  "arg": "Arg kan man vara, men kom ihåg att andas.",
  "orolig": "Oro är normalt, men försök att slappna av.",
  "rolig fakta": "Visste du att sniglar kan sova i tre år?",
  "mysterie": "Mysteries är spännande! Vill du höra ett?",
  "gåta svår": "Vad går upp och ner men rör sig aldrig? Trappor!",
  "alien": "Aliens är fascinerande att fantisera om!",
  "rymd": "Rymden är oändlig och full av hemligheter.",
  "stjärna": "Stjärnor lyser långt borta men ger oss hopp.",
  "planet": "Planeter är vackra och unika.",
  "solsystem": "Vårt solsystem är bara ett av miljarderna i galaxen.",
  "galax": "Galaxer är stora och majestätiska.",
  "svart hål": "Svarta hål är mystiska och kraftfulla.",
  "meteor": "Meteorer kan vara både vackra och farliga.",
  "komet": "Kometen blinkar på himlen, visst är det coolt?",
  "asteroid": "Asteroider kan träffa planeter men är oftast små.",
  "teknologi": "Teknologi gör livet enklare och mer spännande.",
  "robotvän": "Jag är din robotvän!",
  "AI vän": "AI-vänner är alltid redo att lyssna.",
  "cyberspace": "Cyberspace är oändligt och spännande.",
  "internet äventyr": "Äventyr på nätet är alltid roliga!",
  "hack": "Hack är coolt att veta om, men vi ska vara snälla!",
  "kodning": "Kodning är som att bygga magi med logik.",
  "programmera": "Programmering är roligt och utmanande!",
  "app idé": "Vilken app skulle du vilja göra?",
  "spel utveckling": "Spelutveckling är kreativt och kul!",
  "webb design": "Webbdesign gör sidor snygga och funktionella.",
  "grafik": "Grafik kan göra allt mer levande!",
  "animation": "Animation är som att ge liv åt bilder.",
  "filmidé": "Berätta din filmidé, jag lyssnar!",
  "serieidé": "En ny serie skulle vara spännande!",
  "musik smak": "Vilken musik gillar du mest?",
  "instrument": "Instrument är roliga att spela!",
  "gitarr": "Gitarr är coolt, vill du lära dig spela?",
  "piano": "Piano är vackert och melodiskt.",
  "trummor": "Trummor gör musiken rytmisk och energisk!",
  "sångtalang": "Sång kan uttrycka känslor på ett magiskt sätt.",
  "dansstil": "Dans är roligt och får energi att flöda.",
  "konstnär": "Att skapa konst är fantastiskt!",
  "måla tavla": "Måla tavlor är avkopplande och kreativt.",
  "skiss": "Skisser är första steget till konstverk.",
  "bok läsning": "Böcker tar dig till andra världar.",
  "skriva": "Att skriva är ett sätt att uttrycka sig.",
  "novell": "Noveller är korta men spännande berättelser.",
  "poesi": "Poesi kan kännas i hela kroppen.",
  "blogg": "Bloggar är roliga att läsa och skriva.",
  "journal": "Journaler hjälper dig minnas och reflektera.",
  "dagbok": "Dagböcker är som hemliga vänner.",
  "humor": "Humor gör livet roligare!",
  "rolig historia": "Berätta en rolig historia, jag älskar skämt!",
  "skämtar": "Jag gillar skämt, speciellt ordlekar!",
  "meme": "Memes gör internet roligt!",
  "video": "Videor är roliga och informativa.",
  "stream": "Streaming är populärt och kul!",
  "youtuber": "YouTubers skapar fantastiskt innehåll!",
  "tiktok": "TikTok är fullt av roliga klipp.",
  "sociala medier": "Sociala medier är ett bra sätt att hålla kontakt.",
  "community": "Communities är kul och lärorika.",
  "forum": "Forum är perfekta för att diskutera idéer.",
  "chat": "Chattar är roliga när man kan prata fritt.",
  "vän chat": "Vänchat är mysigt och tryggt.",
  "spel chat": "Spelchat är alltid full av roliga kommentarer!",
  "emoji": "Emojis gör texten roligare! 😄",
  "smiley": "Smiley gör allt mer glatt! 😊",
  "cool": "Cool är alltid kul att höra!",
  "awesome": "Awesome! Helt fantastiskt!",
  "fantastiskt": "Fantastiskt att du är här!",
  "wow": "Wow! Så spännande!",
  "oops": "Oops! Det händer oss alla ibland.",
  "haha": "Haha, det var roligt!",
  "lol": "LOL! Skrattar med dig!",
  "hihi": "Hihi! Så gulligt sagt!",
  "nyhet": "Nyheter är alltid intressanta.",
  "artikel": "Artiklar kan lära oss mycket.",
  "tidning": "Tidningar är bra för information.",
  "bokhandel": "Bokhandel är som ett paradis för läsare.",
  "bibliotek": "Bibliotek är magiska platser fulla av böcker.",
  "spel butik": "Spelbutiker har allt för gamers!",
  "leksaksbutik": "Leksaksbutiker är roliga att utforska.",
  "museum": "Museer är fyllda av historia och kultur.",
  "konsert": "Konserter är fulla av energi och musik.",
  "festival": "Festivaler är roliga och festliga!",
  "evenemang": "Evenemang är roliga att delta i.",
  "kalas": "Kalas är alltid kul!",
  "födelsedagskalas": "Födelsedagskalas är speciella dagar.",
  "julklapp": "Julklappar gör alla glada!",
  "påskägg": "Påskägg är roliga att leta efter.",
  "semester dröm": "Semesterdrömmar är underbara!",
  "strand": "Stranden är perfekt för sol och bad.",
  "pool": "Poolen är svalkande och kul!",
  "vinterlek": "Vinterlek är mysigt med snö!",
  "snögubbe": "Snögubbar är roliga att bygga!",
  "pulkabacke": "Pulka är kul för både barn och vuxna.",
  "skogspromenad": "Skogspromenader är lugnande och friska.",
  "bergsklättring": "Bergsklättring är spännande men utmanande!",
  "cykeltur": "Cykelturer är roliga och nyttiga.",
  "löpning": "Löpning håller kroppen i form.",
  "fotvandring": "Fotvandring är perfekt för naturälskare.",
  "camping": "Camping är kul och äventyrligt!",
  "båtresa": "Båtresor är mysiga och lugnande.",
  "segling": "Segling är både roligt och lärorikt.",
  "fiske": "Fiske är avkopplande och spännande.",
  "djurpark": "Djurparker är roliga och lärorika.",
  "akvarium": "Akvarier är fascinerande att titta på.",
  "zoo": "Zoo är fulla av spännande djur.",
  "hundvalp": "Hundvalpar är söta och busiga!",
  "kattungar": "Kattungar är mjuka och lekfulla!",
  "papegoja": "Papegojor kan lära sig prata!",
  "kanin": "Kaniner är fluffiga och snälla.",
  "hamster": "Hamstrar är små och roliga husdjur.",
  "sköldpadda": "Sköldpaddor lever länge och är tåliga.",
  "fågelbur": "Fåglar i bur behöver mycket omsorg.",
  "akvariefisk": "Akvariefiskar är vackra och färgglada.",
  "matlagning": "Matlagning är kreativt och gott!",
  "recept": "Recept hjälper oss göra god mat.",
  "kaka": "Kakor är alltid gott!",
  "bröd": "Färskt bröd luktar fantastiskt.",
  "pasta": "Pasta är enkel och god mat.",
  "soppa": "Soppa är värmande och nyttig.",
  "frukt": "Frukt är gott och nyttigt.",
  "grönsaker": "Grönsaker är viktiga att äta!",
  "äppeljuice": "Äppeljuice är friskt och gott!",
  "smoothie": "Smoothies är både goda och hälsosamma.",
  "kaffe": "Kaffe piggar upp många!",
  "te": "Te är lugnande och gott.",
  "chokladmousse": "Chokladmousse är mumsigt!",
  "glassstrut": "Glassstrut är perfekt på sommaren!",
  "sallad": "Sallad är fräscht och nyttigt.",
  "middag": "Middag är mysigt att äta tillsammans.",
  "frukost": "Frukost är dagens viktigaste mål.",
  "lunch": "Lunch är perfekt för att fylla på energi."
};
