const aiResponses = {
  "hej": "Hej på dig!",
  "tja": "Tja! Hur är läget?",
  "hur mår du": "Jag mår bra, tack! Och du?",
  "vad heter du": "Jag heter WindskoreAI?",
  "sluta": "Hejdå! Vi ses nästa gång.",
  
  // Nya 100 nyckelord/svar
  "god morgon": "God morgon! Hoppas du sovit gott!",
  "god natt": "God natt! Sov så gott!",
  "vad gör du": "Jag pratar med dig just nu!",
  "spelar du spel": "Ja, jag gillar spel! Vilket är ditt favoritspel?",
  "favoritfärg": "Jag gillar blått, det är lugnande.",
  "vad är klockan": "Jag har ingen klocka, men jag kan alltid gissa! 😄",
  "väder": "Jag hoppas solen skiner där du är!",
  "regn": "Regn är mysigt ibland, eller hur?",
  "sol": "Sol är alltid härligt!",
  "snö": "Snö kan vara vackert men kallt.",
  "roligt": "Jag älskar roliga saker!",
  "tråkigt": "Tråkigt kan man göra om till något kul!",
  "musik": "Jag gillar musik, speciellt lugn bakgrundsmusik.",
  "film": "Vilken typ av filmer gillar du?",
  "serie": "Serier är perfekt för en mysig kväll.",
  "mat": "Mat är livet! Vad gillar du att äta?",
  "pizza": "Pizza är alltid ett bra val!",
  "glass": "Glass på sommaren är bäst!",
  "hund": "Hundar är så söta!",
  "katt": "Katter är mysiga och självständiga.",
  "spel": "Vilket spel spelar du just nu?",
  "minecraft": "Minecraft är superkul! Vad bygger du?",
  "roblox": "Roblox är kul! Har du något eget spel där?",
  "programmering": "Programmering är spännande! Vilket språk använder du?",
  "javascript": "JavaScript är väldigt användbart för webben!",
  "lua": "Lua är perfekt för spelmodding och Roblox.",
  "c++": "C++ är kraftfullt men lite mer avancerat.",
  "python": "Python är enkelt och roligt att använda!",
  "html": "HTML är grunden för alla webbsidor.",
  "css": "CSS gör webben snygg och stilren.",
  "hemligt": "Shhh... det är hemligt!",
  "skämt": "Varför kan inte ett spöke ljuga? För man ser rakt igenom det! 😄",
  "gåta": "Vad har tänder men kan inte äta? Ett sågblad!",
  "robot": "Jag är en AI-robot, men vänlig såklart!",
  "AI": "Jag är en AI och jag gillar att prata med dig!",
  "framtid": "Framtiden är spännande, full av möjligheter!",
  "teknik": "Teknik gör livet enklare på många sätt.",
  "dator": "Jag älskar datorer, de är som mina vänner!",
  "mobil": "Mobiltelefoner är praktiska, men glöm inte vila från dem!",
  "internet": "Internet är stort, men vi kan hitta allt där!",
  "wifi": "WiFi är som luft för en dator.",
  "skola": "Skola är viktigt, men glöm inte ha kul också!",
  "läxa": "Läxor kan vara tråkiga, men de hjälper dig växa.",
  "lärare": "Lärare är fantastiska och lär oss mycket.",
  "vän": "Vänner är guld värda!",
  "familj": "Familj är viktigt, ta hand om dem!",
  "semester": "Semester är perfekt för att vila och ha kul.",
  "resa": "Resor är roliga och lärorika.",
  "bil": "Bilar är snabba och coola!",
  "cykel": "Cykla är både kul och nyttigt!",
  "flygplan": "Flygplan är fantastiska, de tar oss över världen!",
  "båt": "Båtar är mysiga på vattnet.",
  "hav": "Havet är stort och vackert!",
  "sjö": "Sjön är perfekt för en picknick eller simtur.",
  "berg": "Berg är mäktiga och imponerande.",
  "skog": "Skogen är lugn och fridfull.",
  "djur": "Djur är underbara och roliga att observera.",
  "fågel": "Fåglar kan vara vackra och sjunga fint.",
  "fisk": "Fiskar är fascinerande att titta på.",
  "äpple": "Äpplen är goda och nyttiga!",
  "banan": "Bananer är enkla att äta och ger energi.",
  "choklad": "Choklad är alltid gott!",
  "godis": "Godis kan vara festligt ibland!",
  "sport": "Sport är roligt och bra för kroppen.",
  "fotboll": "Fotboll är världens mest populära sport!",
  "basket": "Basket är kul och actionfyllt!",
  "tennis": "Tennis är både teknik och kraft.",
  "spelplan": "En spelplan är platsen för roliga matcher!",
  "konst": "Konst är ett sätt att uttrycka sig.",
  "måla": "Måla är avslappnande och kreativt.",
  "rita": "Att rita är alltid kul!",
  "musikstil": "Vilken musikstil gillar du mest?",
  "dans": "Dans är roligt och energigivande!",
  "sång": "Sång kan göra folk glada.",
  "bok": "Böcker är som portaler till andra världar.",
  "läsning": "Att läsa är både roligt och lärorikt.",
  "filmkväll": "Filmkvällar är mysiga!",
  "bio": "Att gå på bio är alltid en upplevelse.",
  "shopping": "Shopping kan vara kul men tröttsamt!",
  "present": "Presenter gör folk glada.",
  "födelsedag": "Födelsedagar är speciella dagar!",
  "jul": "Jul är mysigt med familj och ljus.",
  "påsk": "Påsk handlar om ägg och roliga traditioner.",
  "sommar": "Sommar är perfekt för semester och sol.",
  "vår": "Vår är vacker med alla blommor.",
  "höst": "Höstens färger är fantastiska.",
  "vinter": "Vinter är mysigt med snö och varm choklad.",
  "semesterplaner": "Har du några roliga semesterplaner?",
  "dröm": "Drömmar kan vara både roliga och konstiga!",
  "idé": "Bra idé! Berätta mer.",
  "problem": "Problem är till för att lösas!",
  "hjälp": "Självklart, jag hjälper dig gärna!",
  "fråga": "Ställ din fråga, jag lyssnar!",
  "nyfiken": "Nyfikenhet är nyckeln till lärande!",
  "roligt skämt": "Varför kunde inte cykeln stå upp? Den var två-hjulig! 😄",
  "spelidé": "Berätta om din spelidé, jag är nyfiken!"
};
